# Generated by Django 4.1.5 on 2023-01-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StackToolsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('salary_from', models.PositiveIntegerField(null=True)),
                ('salary_to', models.PositiveIntegerField(null=True)),
                ('speciality', models.CharField(max_length=64)),
                ('experience', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=16)),
                ('link', models.URLField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('stack', models.ManyToManyField(null=True, to='vacancies_app.stacktools')),
            ],
        ),
        migrations.AddField(
            model_name='stacktools',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies_app.stacktoolscategory'),
        ),
    ]
