# Generated by Django 4.1.5 on 2023-01-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='МИАЦ', max_length=128)),
                ('country', models.CharField(default='Россия', max_length=32, null=True)),
                ('city', models.CharField(default='Москва', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_from', models.PositiveIntegerField(null=True)),
                ('salary_to', models.PositiveIntegerField(null=True)),
                ('speciality', models.CharField(max_length=64, null=True)),
                ('experience', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=16, null=True)),
                ('link', models.URLField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vacancies_app.company')),
                ('stack', models.ManyToManyField(to='vacancies_app.stacktools')),
            ],
        ),
    ]
