# Generated by Django 4.1.5 on 2023-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='stack',
            field=models.ManyToManyField(to='vacancies_app.stacktools'),
        ),
    ]
