# Generated by Django 4.1.5 on 2023-01-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_app', '0002_alter_vacancy_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(default='Россия', max_length=32)),
                ('city', models.CharField(default='Москва', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vacancies_app.company'),
        ),
    ]
