export const GENERAL_VACANCIES = 'VACANCIES/GENERAL';

export const FILTER_SPECIALITIES = 'FILTER_VALUES/SPECIALITIES';
export const FILTER_GRADES = 'FILTER_VALUES/GRADES';
export const FILTER_CITIES = 'FILTER_VALUES/CITIES';
export const FILTER_EXPIRIENCES = 'FILTER_VALUES/EXPIRIENCES';
export const FILTER_STACKTOOLS = 'FILTER_VALUES/STACKTOOLS';

export const COUNT_ON_PAGE_10 = 'COUNT_ON_PAGE/10';
export const COUNT_ON_PAGE_30 = 'COUNT_ON_PAGE/30';
export const COUNT_ON_PAGE_50 = 'COUNT_ON_PAGE/50';