export const GET_GENERAL_VACANCIES = 'VACANCIES/GENERAL';
export const GET_GENERAL_VACANCIES_SUCCESS = 'VACANCIES/GENERAL_SUCCESS';
export const GET_GENERAL_VACANCIES_ERROR = 'VACANCIES/GENERAL_ERROR';

export const PAGINATION_SET_PAGE = 'PAGINATION/SET_PAGE';
export const PAGINATION_SET_COUNT_ON_PAGE = 'PAGINATION/SET_COUNT_ON_PAGE';

export const FILTER_SPECIALITIES = 'GET_FILTER_VALUES/SPECIALITIES';
export const FILTER_GRADES = 'GET_FILTER_VALUES/GRADES';
export const FILTER_CITIES = 'GET_FILTER_VALUES/CITIES';
export const FILTER_EXPIRIENCES = 'GET_FILTER_VALUES/EXPIRIENCES';
export const FILTER_STACKTOOLS = 'GET_FILTER_VALUES/STACKTOOLS';
export const FILTER_VALUES_ERROR = 'GET_FILTER_VALUES/ERROR';

export const SET_FILTER_SPECIALITY = 'SET_FILTER_VALUES/SPECIALITY';
export const SET_FILTER_GRADE = 'SET_FILTER_VALUES/GRADE';
export const SET_FILTER_CITY = 'SET_FILTER_VALUES/CITY';
export const SET_FILTER_EXPERIENCE = 'SET_FILTER_VALUES/EXPERIENCES';
export const SET_FILTER_STACKTOOL = 'SET_FILTER_VALUES/STACKTOOL';
export const SET_FILTER_VALUE_CLEAR = 'SET_FILTER_VALUES/CLEAR';
export const SET_FILTER_SALARY = 'SET_FILTER_VALUES/SALARY';
export const SET_FILTER_REMOTE = 'SET_FILTER_VALUES/REMOTE';
