export const GET_GENERAL_VACANCIES = 'VACANCIES/GENERAL';
export const GET_GENERAL_VACANCIES_SUCCESS = 'VACANCIES/GENERAL_SUCCESS';
export const GET_GENERAL_VACANCIES_ERROR = 'VACANCIES/GENERAL_ERROR';

export const PAGINATION_SET_PAGE = 'PAGINATION/SET_PAGE';
export const PAGINATION_SET_COUNT_ON_PAGE = 'PAGINATION/SET_COUNT_ON_PAGE';

export const FILTER_SPECIALITIES = 'FILTER_VALUES/SPECIALITIES';
export const FILTER_GRADES = 'FILTER_VALUES/GRADES';
export const FILTER_CITIES = 'FILTER_VALUES/CITIES';
export const FILTER_EXPIRIENCES = 'FILTER_VALUES/EXPIRIENCES';
export const FILTER_STACKTOOLS = 'FILTER_VALUES/STACKTOOLS';